#############################################################################################
# General settings for TAP                                                                  #
# The full installation profile used and the ingress address + default registry is set here #
#############################################################################################
profile: full
ceip_policy_disclosed: true
shared:
  ingress_domain: tap.viktoriouslab.nl
  image_registry:
    project_path: <your-tap-registry>
    # This secret is created in step 05/05b
    secret:
      name: tap-registry
      namespace: tap-install
tap_telemetry:
  customer_entitlement_account_number: ""

#############################################################################################
# Use a git repository for K8S yaml distribution (using GitOps instead of RegistryOps)      #
#############################################################################################
ootb_supply_chain_testing_scanning:
  gitops:
    # This secret contains the credentials for the git repossh_secret: git-https-secret:
    branch: main
    commit_message: "Update from TAP Supply Chain Choreographer"
    server_address: https://github.com/
    # Github-account we're using:
    repository_owner: viktoriousss 
    repository_name: tap-deliveries

#############################################################################################
# The namespace provisioner is responsible for setting up developer namespaces in your      #
# environment. The configuration is contained on a Git Repository and contains the          #
# namespaces to be created ws well as the default resources that should be added to these   #
# namespaces.                                                                               #
#############################################################################################
namespace_provisioner:
  controller: false
  sync_period: 30s
  # Namespace provisioner - list of namespaces
  gitops_install:
    ref: origin/main
    subPath: tap/ns-provisioner/namespaces
    url: https://github.com/viktoriousss/tanzu-demo-essentials.git
  # Namespace provisioner - additional resources
  additional_sources:
    - git:
        url: https://github.com/viktoriousss/tanzu-demo-essentials.git  
        ref: origin/main
        subPath: tap/ns-provisioner/namespaces-resources        
        secretRef:
          name: git-https-secret # this is the new credential
          namespace: tap-install
          #create_export: true
  #import_data_values_secrets:
  #  - name: git-https-secret
  #    namespace: tap-install
  #    create_export: true
  # This account is used for doing GitOps with Supply Chain Choreographer
  default_parameters:
    supply_chain_service_account:
      secrets:
      - git-https-secret

supply_chain: testing_scanning
metadata_store:
  ns_for_export_app_cert: "*"

#############################################################################################
# Configuration of TAP-GUI specific settings                                                #
#############################################################################################
tap_gui:
  # TLS certificate configuration for TAP-GUI
  tls:
    namespace: cert-manager
    secretName: tap-gui
  app_config:
    customize:
      custom_name: "viktorious.nl Developer Portal"
    organization:
      name: "viktorious.nl"
    # GitHub authentication configuration
    auth:
      allowGuestAccess: false
      environment: development
      providers:
        github: # This is for github OAuth authentication to the TAP portal. Configure a new OAuth app for TAP here: https://github.com/settings/developers. Homepage URL is http://tap-gui.<ingress-domain configured earlier>.
          development:
            clientId: ""  # you need to get this value from GitHub Developer Settings OAuth2 page
            clientSecret: ""
#
#excluded_packages:
#  - crossplane.tanzu.vmware.com
#  - bitnami.services.tanzu.vmware.com
# Add custom Backstage plugins here                                                         #
#package_overlays:
#- name: tap-gui
#  secrets:
#  - name: tdp-app-image-overlay-secret

